def project = "tonal-justice-216711"
def  appName = "jenkins-sampleapp"
def  feSvcName = "sampleapp-svc"
def  imageTag = "eu.gcr.io/${project}/${appName}:${env.BRANCH_NAME}.${env.BUILD_NUMBER}"

pipeline {
  agent {
    kubernetes {
      label 'sample-app'
      defaultContainer 'jnlp'
      yaml """
apiVersion: v1
kind: Pod
metadata:
labels:
  component: ci
spec:
  # Use service account that can deploy to all namespaces
  serviceAccountName: cd-jenkins
  containers:
  - name: gcloud
    image: gcr.io/cloud-builders/gcloud
    command:
    - cat
    tty: true
  - name: kubectl
    image: gcr.io/cloud-builders/kubectl
    command:
    - cat
    tty: true
"""
}
  }
  stages {
    stage('Build and push image to GCR') {
      steps {
        container('gcloud') {
          sh "PYTHONUNBUFFERED=1 gcloud builds submit -t ${imageTag} ."
        }
      }
    }
    stage('Deploy Canary') {
      // Canary branch
      when { branch 'canary' }
      steps {
        container('kubectl') {
          // Change deployed image in canary to the one we just built
          sh("sed -i.bak 's#eu.gcr.io/tonal-justice-216711/jenkins-sampleapp#${imageTag}#' ./k8s-app/sampleapp-canary.yaml")
          sh("kubectl --namespace=live-app apply -f k8s-app/sampleapp-service.yaml")
          sh("kubectl --namespace=live-app apply -f k8s-app/sampleapp-canary.yaml")
        } 
      }
    }
    stage('Deploy Production') {
      // Production branch
      when { branch 'master' }
      steps{
        container('kubectl') {
        // Change deployed image in production to the one we just built
          sh("sed -i.bak 's#eu.gcr.io/tonal-justice-216711/jenkins-sampleapp#${imageTag}#' ./k8s-app/sampleapp-production.yaml")
          sh("kubectl --namespace=live-app apply -f k8s-app/sampleapp-service.yaml")
          sh("kubectl --namespace=live-app apply -f k8s-app/sampleapp-production.yaml")
        }
      }
    }
    stage('Deploy Dev') {
      // Development branches
      when { 
        not { branch 'master' } 
        not { branch 'canary' }
      } 
      steps {
        container('kubectl') {
          // New namespace for created branch
          sh("kubectl get ns ${env.BRANCH_NAME} || kubectl create ns ${env.BRANCH_NAME}")
          // We will change the load balancer service type for ClusterIP, as we don't want our development branch app to be publicly accessed
          sh("sed -i.bak 's#LoadBalancer#ClusterIP#' ./k8s-app/sampleapp-service.yaml")
          sh("sed -i.bak 's#eu.gcr.io/tonal-justice-216711/jenkins-sampleapp#${imageTag}#' ./k8s-app/sampleapp-development.yaml")
          sh("kubectl --namespace=${env.BRANCH_NAME} apply -f k8s-app/sampleapp-service.yaml")
          sh("kubectl --namespace=${env.BRANCH_NAME} apply -f k8s-app/sampleapp-development.yaml")
          echo 'To access your environment run `kubectl proxy`'
          echo "Then access your service via http://localhost:8001/api/v1/proxy/namespaces/${env.BRANCH_NAME}/services/${feSvcName}:80/"
        }
      }     
    }
  }
}
